/**
 * Tooltip Component for ATS Suggestions using react-tooltip
 */
import React from 'react';
import { Tooltip } from 'react-tooltip';

interface TooltipProps {
  whyImportant?: string;
  howToImplement?: string;
  children: React.ReactNode;
  id?: string; // Unique identifier for the tooltip
}

export default function SuggestionTooltip({ whyImportant, howToImplement, children, id }: TooltipProps) {
  if (!whyImportant && !howToImplement) {
    return <>{children}</>;
  }

  const tooltipId = id || `tooltip-${Date.now()}-${Math.floor(performance.now())}`;

  return (
    <>
      <div 
        data-tooltip-id={tooltipId}
        className="inline-block cursor-help"
        aria-describedby={tooltipId}
        tabIndex={0}
        role="button"
        aria-label="Show AI suggestion details"
      >
        {children}
      </div>
      <Tooltip
        id={tooltipId}
        clickable
        place="top"
        style={{
          backgroundColor: '#1f2937',
          color: '#f9fafb',
          borderRadius: '8px',
          padding: '12px',
          maxWidth: '320px',
          fontSize: '14px',
          lineHeight: '1.4',
          zIndex: 1000,
        }}
        role="tooltip"
        aria-live="polite"
      >
        <div className="max-w-sm">
          <div className="mb-2 text-xs text-blue-200 font-semibold">AI-generated content</div>
          {whyImportant && (
            <div className="mb-3">
              <h5 className="font-semibold text-blue-200 mb-2 flex items-center gap-2">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                </svg>
                Why this matters
              </h5>
              <p className="text-gray-200 text-sm leading-relaxed">{whyImportant}</p>
            </div>
          )}
          {howToImplement && (
            <div>
              <h5 className="font-semibold text-green-200 mb-2 flex items-center gap-2">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-13a1 1 0 10-2 0 1 1 0 002 0zm-1 2a1 1 0 00-1 1v3a1 1 0 001 1h1a1 1 0 100-2h-1V8a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
                How to implement
              </h5>
              <p className="text-green-100 text-sm leading-relaxed">{howToImplement}</p>
            </div>
          )}
          <div className="mt-3 text-xs text-gray-400" aria-label="Privacy Notice">
            <strong>Privacy Notice:</strong> This suggestion is generated by AI and anonymized before processing. <a href="/privacy" className="underline">Learn more</a>.
          </div>
        </div>
      </Tooltip>
    </>
  );
}
